version: "3.12"

services:
  nginx:
    build: .
    ports:
    - "80:80"
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./html:/usr/share/nginx/html

  redis:
    image: redis:latest
    restart: on-failure
    ports:
    - '6379'

  db:
    container_name: db
    image: postgres:16
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    env_file:
        - .env

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

  celery:
    build: .
    tty: true
    command: celery -A config worker --loglevel=info
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app
    env_file:
      - .env

volumes:
  pg_data:
  static_volume:
